/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author abate
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMclientes = new javax.swing.JMenu();
        jMIagregarCliente = new javax.swing.JMenuItem();
        jMIbuscarCliente = new javax.swing.JMenuItem();
        jMIborrarCliente = new javax.swing.JMenuItem();
        jMdirectorios = new javax.swing.JMenu();
        jMIbuscarClientePorCiudad = new javax.swing.JMenuItem();
        jMIbuscarTelefonoPorApellido = new javax.swing.JMenuItem();
        jMciudades = new javax.swing.JMenu();
        jMIagregarCiudades = new javax.swing.JMenuItem();
        jMsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        jMclientes.setText("Clientes");

        jMIagregarCliente.setText("Agregar Cliente");
        jMIagregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIagregarClienteActionPerformed(evt);
            }
        });
        jMclientes.add(jMIagregarCliente);

        jMIbuscarCliente.setText("Buscar Cliente");
        jMclientes.add(jMIbuscarCliente);

        jMIborrarCliente.setText("Borrar Cliente");
        jMclientes.add(jMIborrarCliente);

        jMenuBar1.add(jMclientes);

        jMdirectorios.setText("Directorios");

        jMIbuscarClientePorCiudad.setText("Buscar Cliente por Ciudad");
        jMdirectorios.add(jMIbuscarClientePorCiudad);

        jMIbuscarTelefonoPorApellido.setText("Buscar telefono por Apellido");
        jMdirectorios.add(jMIbuscarTelefonoPorApellido);

        jMenuBar1.add(jMdirectorios);

        jMciudades.setText("Ciudades");

        jMIagregarCiudades.setText("Agregar Ciudades");
        jMciudades.add(jMIagregarCiudades);

        jMenuBar1.add(jMciudades);

        jMsalir.setText("Salir");
        jMenuBar1.add(jMsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIagregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIagregarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarCliente ac = new AgregarCliente();
        ac.setVisible(true);
        escritorio.add(ac);
    }//GEN-LAST:event_jMIagregarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMIagregarCiudades;
    private javax.swing.JMenuItem jMIagregarCliente;
    private javax.swing.JMenuItem jMIborrarCliente;
    private javax.swing.JMenuItem jMIbuscarCliente;
    private javax.swing.JMenuItem jMIbuscarClientePorCiudad;
    private javax.swing.JMenuItem jMIbuscarTelefonoPorApellido;
    private javax.swing.JMenu jMciudades;
    private javax.swing.JMenu jMclientes;
    private javax.swing.JMenu jMdirectorios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMsalir;
    // End of variables declaration//GEN-END:variables
}
